### PR TITLE
Added PEET to software resources

### PR DESCRIPTION
**Pull request by jmheumann**
Added an entry for PEET to Software Resources.

Thanks!
-jh-

### CODE REVIEW

**Review by alisterburt — APPROVED** [review]
Great stuff, thank you @jmheumann and sorry for not adding PEET before now!

**Comment by alisterburt** [comment]
This won't show on the website just yet, automatic deployment has failed! Will look into it properly tomorrow 🙂

**Comment by jmheumann** [comment]
Thanks, Alister!

Don't think I did anything out of the ordinary which might have caused
that, but who knows.
FWIW, I had a hard time getting jupyter-book running properly on RHEL7
using "conda install -c python-forge  jupyter-book" (and other
dependencies). Tried several versions of Anaconda, but kept getting errors
when building the book. Finally, I reverted to the latest Anaconda release
and then installed jupyter-book and a couple dependencies with pip. Only
the latter worked.

I'm no Python expert, but it looks to me like the various Python package /
dependency managers aren't really up to the task... too many versions of
too many packages whose compatibility hasn't been verified. (To be fair,
it's probably missing information rather than the package managers which
are at fault). I seem to run into this kind of stuff almost every time I
try to install a Python package with lots of dependencies.

Best,
-jh-





Best,
-jh-

**Comment by brisvag** [comment]
@jmheumann There were a bunch of issues here caused by several outdated dependendencies, because we haven't touched them in a while. I created a PR to address those over at #46. Hopefully once that's merged you won't have all those problems anymore :)

**Comment by jmheumann** [comment]
Thanks, Lorenzo!

**Comment by jmheumann** [comment]
Hi Alister, Lorenzo,

The PEET entry hasn't appeared on the website yet. Are you guys still
working on updating?
Sorry to nag... just wanted to make sure it didn't accidentally fall
through the cracks,

Best,
-jh-

**Comment by brisvag** [comment]
Uhm, something is indeed not working, still... thansk for checking! Something must be different in the CI than my local environment. Trying to fix it now!

**Comment by brisvag** [comment]
Fixed! https://teamtomo.org/resources/cryoet-software/peet/peet.html

**Comment by jmheumann** [comment]
Great, thanks Lorenzo!

Best,
-jh-

**Pull request merged**
